version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"

  web:
    image: nginx:latest
    container_name: web_nginx2
    volumes:
      - ./nginx:/usr/share/nginx/html
    ports:
      - "8081:80"
    restart: always